### ISSUE TITLE
Follower doesn't see posts of followed

### ISSUE THREAD

**Issue by chowlett** [shklnrj/thoughtrightnow#1]
polly is following dodo.
polly is not seeing dodo's  posts.

**Comment by shuklaneerajdev** [comment]
Hi @chowlett 

I just checked it. At the moment dodo is not being followed by anyone other than the default user. There might be confusion because of the ui. Please login as polly and the follow dodo from suggested user list. 
https://imgur.com/a/pec6Gmp

**Comment by chowlett** [comment]
Hi @shklnrj 
Here is some more on this from one of the developers here. https://www.dropbox.com/s/lohegrcb9ujalsf/NeerajBug.mov?dl=0

**Comment by shuklaneerajdev** [comment]
Well @chowlett , i thought it was more natural for someone's post which are created after they have been followed to appear in the feed. 

So if Polly follows Dodo, from now on, when Dodo makes post, it will appear in Polly's feed.  

In this case, Dodo's new posts will show up in Polly's not the older ones.
